### PR TITLE
Added instructions how to get Focus working on Mac OS X.

### PR DESCRIPTION
**Pull request by kjagiello**
Simple instructions how to configure DNS on Mac OS X to work with Focus.

### CODE REVIEW

**Comment by amoffat** [comment]
Thanks!  I have a question though... focus.py reads in the nameservers from /etc/resolv.conf, so that it knows which one to forward certain requests to.  If Mac doesn't use resolv.conf, can you think of a good way for focus to know about the other nameservers?

**Comment by kjagiello** [comment]
It seems that Mac OS X uses /etc/resolv.conf to store the address of the nameserver. I'm far away from my Mac right now, but I will check that for you tommorow if nobody helps you with that before me.

**Comment by kjagiello** [comment]
```
Krzysztof-Jagiellos-MacBook:~ krzysztofjagiello$ cat /etc/resolv.conf 
#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#
domain adm.ovansiljan.net
nameserver 192.168.1.12
nameserver 192.168.1.13
```

**Comment by amoffat** [comment]
perfect, ok it should work fine then

**Comment by cdetrio** [comment]
The problem isn't focus.py being able to use /etc/resolv.conf. It is that the web browser (eg Chrome) does not resolve domains using resolv.conf ("most processes" as mentioned in the header), so even if 127.0.0.1 is in resolv.conf, the domain name requests made by the web browser never route to 127.0.0.1 (unless it is added to the DNS servers in the Mac system preferences) and therefore never to focus.py.

**Comment by amoffat** [comment]
Moving the discussion to issue #8

**Pull request merged**
