### PR TITLE
Keep TTL unchanged for hosts that are not blacklisted

### PR DESCRIPTION
**Pull request by ghost**
I'm not sure how much of a difference this would have in practice - AFAIR, some browsers do have their own local DNS caches with their own arbitrary TTLs (for Chrome, it's one minute) as they do not have access to those returned along with the DNS records. But it seems like the right thing to do, especially for slower DNS servers.

In general though, it'd probably be better to have the server return only invalid records for blacklisted domains and unknown host responses for others and just let the OS try with the other servers and handle the TTLs properly (right now, only the first name server is tried for non-blacklisted hosts).

### CODE REVIEW

**Comment by amoffat** [comment]
It's an issue though for the services/browsers that do remember ip TTLs...what ends up happening is the firewall kicks in, but the service is still using the old ip.

But your point about focus only using that first nameserver...yeah that needs to be fixed :)  I'm not 100% sure how it should work, but possibly forward the request to all nameservers at once, and then only return a non-error response to the requester?

**Comment by ghost** [comment]
@amoffat Browsers/services can't actually remember TTLs (the OS doesn't expose them) unless they implement their own DNS lookup. So they either use an arbitrary TTL for their own caches or they just let the OS cache things. For that reason, even at this point, focus probably doesn't work very reliably anyway.

But this change only addresses the hosts that do not have the corresponding handler at all with the assumption that typically one wouldn't change the blacklist (i.e. add new predicates) very often and can handle some hiccup when doing so. Adjusting all the DNS lookups with a near-zero TTL (even if it doesn't affect certain browsers) is just a performance killer.

Re: my second point, yes, all the name servers from the resolv.conf should be used. But I just don't think it's the job for focus. It should return an unsuccessful lookup response and let the OS try with the next name servers. That would make it impossible to alter TTLs but if you did this only for domains without predicates, that'd be an improvement.

Another way to do this cleanly would be perhaps to figure out how you can clear the DNS cache for different OSes and try to do that periodically - say, 1 minute or whatever the ideal time resolution should be.

I forgot to mention, great work with this project! :)

**Comment by amoffat** [comment]
> I forgot to mention, great work with this project! :)

Thanks!

> Adjusting all the DNS lookups with a near-zero TTL (even if it doesn't affect certain browsers) is just a performance killer.

Honestly I haven't noticed any performance hit from my uses.  Are you seeing a big slow down?

One thing I thought of adding would be a local ip cache in focus itself.  So although we respond to everything with a small TTL, we don't actually send out a forwarded lookup if we have the ip in memory that expires based on the TTL we received from our last forwarded request.

> Re: my second point, yes, all the name servers from the resolv.conf should be used.

I realized they are actually being used as-is.  The flow would be like this:  OS does a lookup on domain.com, asks focus, focus doesn't have a rule for it, asks nameserver 2 in resolv.conf, nameserver 2 doesn't know, replies with unknown, OS asks...nameserver 2 (again), then 3, etc.  The only inefficiency there is that 2 get's asked twice before it goes onto 3.  This is trivial to fix, by making focus use the last nameserver instead of the second.

So with all nameservers being used, I don't see much of a gain of not adjusting the ttl, unless you're seeing performance degradation.  Even then, you can raise the ttl in the config.  Am I missing what you're saying?

**Comment by ghost** [comment]
> Honestly I haven't noticed any performance hit from my uses. Are you seeing a big slow down?

I don't have any numbers to back this up and I have a pretty fast DNS server but for someone with slow DNS lookups, the difference may be noticeable.

> One thing I thought of adding would be a local ip cache in focus itself. So although we respond to everything with a small TTL, we don't actually send out a forwarded lookup if we have the ip in memory that expires based on the TTL we received from our last forwarded request.

That would be reimplementing another thing that the OS is already supposed to do and does well.

> I realized they are actually being used as-is. The flow would be like this: OS does a lookup on domain.com, asks focus, focus doesn't have a rule for it, asks nameserver 2 in resolv.conf, nameserver 2 doesn't know, replies with unknown, OS asks...nameserver 2 (again), then 3, etc. The only inefficiency there is that 2 get's asked twice before it goes onto 3. This is trivial to fix, by making focus use the last nameserver instead of the second.

Correct. But that sounds arbitrary. focus should not know about other name servers (and you would get Windows support for free).

> So with all nameservers being used, I don't see much of a gain of not adjusting the ttl, unless you're seeing performance degradation. Even then, you can raise the ttl in the config. Am I missing what you're saying?

All I'm saying is focus does too much. The OS can already do DNS redundancy and cache resolutions. The only thing focus should do is to act as a standalone name server: resolve temporarily blacklisted domains to invalid IPs and let the OS use other name servers for others. If OS-level or browser-level resolution caching degrades the time resolution of the filters, then it should try to flush the caches periodically. I doubt anyone would expect less than a minute of accuracy for predicates anyway.

**Comment by amoffat** [comment]
> for someone with slow DNS lookups, the difference may be noticeable.

I think if their DNS is slow in the first place, they're going to be annoyed by that slowness before they ever add focus.  TTLs of popular sites seem to be quite low these days anyways... I just dig'ed github and got 75 seconds.  Facebook gave 2600 seconds, reddit gave 20 seconds.  If a browser cache is every minute, they're already fetching lookups every few minutes for many sites anyways, so focus is not going to add a noticeable burden.

Which weakens my argument of fine-grained resolution being needed by touching all the responses :)  But see the next paragraph...

> That would be reimplementing another thing that the OS is already supposed to do and does well.

It is, but it allows for more possibilities.  By removing the proxy functionality from focus (which isn't covered by this patch, since it still does forwarding requests, and we would need to respond with an 'unknown' response) it's limited as as just a regular dns server.  By making it a dns proxy, there's potential to build other adaptations.  You might want complete DNS control over your machine, one that the OS can't subvert.  I think there's potential in that.

So I don't think the gain of removing the functionality we're talking about is big enough, but I do see your point (and I think you make good ones) that conceptually, focus should not need to touch other responses to achieve its goal.  But I want to leave the possibility for other adaptations, so I'll have to cast my vote as "no" on this one.  If still feel strongly about it and wanted to start a fork, I wouldn't be offended.  Thank you for the insights and discussion!

**Pull request closed without merging**
